//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvinciaMunicipio
    {
        public System.Guid gid { get; set; }
        public string Provincia { get; set; }
        public string Municipio { get; set; }
    }
}
